### ISSUE TITLE
Error al descargar grabaciones

### ISSUE THREAD

**Issue by jmalaver1712** [zerausolrac/PyCollab#10]
Buen día

Al intentar descargar las grabaciones de Collaborate con ayuda del reporte de grabaciones me arroja el siguiente error.

PS D:\PyCollab> python CollabRecordingsDownload.py -f RecordingReport.csv

Traceback (most recent call last):
  File "CollabRecordingsDownload.py", line 15, in <module>
    recordings_ids = ut.readCollabReport(param[0])
  File "D:\PyCollab\Utilidades.py", line 97, in readCollabReport
    recording = recording_id(register['RecordingLink'])
KeyError: 'RecordingLink'

Me pueden ayudar por favor 
Gracias

**Comment by zerausolrac** [comment]
Puedes por favor verificar que el archivo RecordingReport.csv sea el que descargaste desde Collaborate Scheduler / Reports / Institutional Reports / Recordings report?  Este reporte se descarga en formato CSV, tal archivo debe tener como separador el carácter "," para su ejecución.

**Comment by jmalaver1712** [comment]
Buen día
Muchas gracias por la información
al intentarlo con el archivo tal cual como se descarga, me arroja el siguiente mensaje

PS D:\PyCollab> python CollabRecordingsDownload.py -f 01_RecordingReport.csv

Traceback (most recent call last):
  File "CollabRecordingsDownload.py", line 15, in <module>
    recordings_ids = ut.readCollabReport(param[0])
  File "D:\PyCollab\Utilidades.py", line 97, in readCollabReport
    recording = recording_id(register['RecordingLink'])
  File "D:\PyCollab\Utilidades.py", line 84, in recording_id
    splitedURL = url.split('/')
AttributeError: 'NoneType' object has no attribute 'split'

Adjunto una sección del archivo descargado en formato TXT. 
[01_RecordingReport.txt](https://github.com/zerausolrac/PyCollab/files/5711251/01_RecordingReport.txt)

**Comment by jmalaver1712** [comment]
Buen día

Muchas gracias, ya logramos descargar las grabaciones.
Creo que al abrirlo en excel el archivo se dañaba o cambiaba los delimitadores.

Que tengan muy buen día

**Comment by jmalaver1712** [comment]
Buen día

Al intentar descargar masivamente las grabaciones, en algun momento se detiene la descarga por un error.
Muestra el siguiente mensaje


./downloads/65bfcf18327d42e7bdd918e13cb5efd2-Tercera Sesión "Constitución Política" - recording_1.mp4
  0%|                                                                                     | 0.00/7.09M [00:00<?, ?iB/s]T
raceback (most recent call last):
  File "CollabRecordingsDownload.py", line 35, in <module>
    ut.downloadRecordingsUUID(recording_lista)
  File "F:\PyCollab_07\Utilidades.py", line 205, in downloadRecordingsUUID
    descargarGrabacion(recording_lista['downloadUrl'],fullpath + filename)
  File "F:\PyCollab_07\Utilidades.py", line 122, in descargarGrabacion
    with open(fname,'wb') as file:
OSError: [Errno 22] Invalid argument: './downloads/65bfcf18327d42e7bdd918e13cb5efd2-Tercera Sesión "Constitución Polític
a" - recording_1.mp4'
  0%|                                                                                     | 0.00/7.09M [00:00<?, ?iB/s]


Hay alguna forma de forzar la continuación del script y que no se detenga por este tipo de errores.
Muchas gracias.

**Comment by zerausolrac** [comment]
Hola, al ver el detalle, veo que posiblemente el nombre de la grabación tiene los caracteres de commillas " 
65bfcf18327d42e7bdd918e13cb5efd2-Tercera Sesión **"Constitución Polític
a"** - recording_1.mp4 y eso este afectando en la creación del archivo

He realizado un ajuste, intenta descargar el script nuevamente y probarlo.

**Comment by mqatrawi** [comment]
Hola ,
Cuando intento el código, siempre recibo un mensaje de error.
Su json "Config.py no es válido"
¿Puede aconsejarme qué comprobar?

**Comment by zerausolrac** [comment]
Hola,
Entiendo que el script funcionaba bien, solo una verificación, ¿todos los campos del archivo Config.py estan completos? Quizas aunque solo se usen los campos de Collaborate, los de Learn al menos deben tener en la relación key-value el value como:  " "  (comillas abre y cierra)

**Comment by mqatrawi** [comment]
Muchas gracias.
> Hola,
> Entiendo que el script funcionaba bien, solo una verificación, ¿todos los campos del archivo Config.py estan completos? Quizas aunque solo se usen los campos de Collaborate, los de Learn al menos deben tener en la relación key-value el value como: " " (comillas abre y cierra)

**Comment by zerausolrac** [comment]
Funciono ya el script?

**Comment by mqatrawi** [comment]
Muchas gracias
Si, esta funcionando bien
