### ISSUE TITLE
Ability to pull recordings based on recording ID

### ISSUE THREAD

**Issue by parsonsalan1** [zerausolrac/PyCollab#12]
A really nice feature would be the ability to pull recordings based on their Recording ID and not just the UUID that is associated to a course. Some recordings are not in a course and the only way to get that is through the recording report that has to be manually created... But if this can be modified to pull recording ID, all recordings can be downloaded with their ID's only and no report or course names are needed.

**Comment by zerausolrac** [comment]
Hi @parsonsalan1  sorry for the daley on response, I have implemented that idea, you need to create a file (in this case recordingids_list.txt) where you place recordings_ids as 1 column list and execute the command:

`python CollabRecordingIdList.py -f recordingids_list.txt`

let me know if this works, so I can add it on the README doc!
