### ISSUE TITLE
Destination Folder

### ISSUE THREAD

**Issue by erpdevopseng** [zerausolrac/PyCollab#17]
This looks really great! Has anyone translated it to english? What folder do the videos and data download to? Can you run the script on PC and specify a destination folder on the local area network? I don't see anything on python web searching about PEP 157 package instalation. But I see something on PEP 517. Is that a typo?

**Comment by zerausolrac** [comment]
the video downloaded go to **downloads** folder and the report go to **reports** folder on the root directory of the project.
Yes, the script can run on PC, maybe need to check all dependencies and path values  on PATH env variable on the terminal, I think is possible to perform the idea you have over a network maybe by using ssh

**Comment by erpdevopseng** [comment]
Thanks for your reply
