### ISSUE TITLE
auth:setToken ERROR: Response 400

### ISSUE THREAD

**Issue by gleidsonlm** [zerausolrac/PyCollab#4]
Hi,

I've found other error, this seems to be related to when the Learn REST API application has reached its maximum requests quota:

```
[auth:setToken()] ERROR: <Response [400]>
[auth:setToken()] ERROR: <Response [400]>
Traceback (most recent call last):
  File "/usr/local/opt/PyCollab/controladores/AuthControlador.py", line 57, in getToken
    token = self.cache['token']
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Collab.py", line 16, in <module>
    course_uuids.append(webService.getUUID(curso))
  File "/usr/local/opt/PyCollab/webService.py", line 58, in getUUID
    credencial = {'Authorization' : 'Bearer ' + self.getToken()}
  File "/usr/local/opt/PyCollab/webService.py", line 35, in getToken
    return(self.sesion.getToken())
  File "/usr/local/opt/PyCollab/controladores/AuthControlador.py", line 67, in getToken
    return self.cache['token']
TypeError: 'NoneType' object is not subscriptable
```

Guessing it would be helpful to handle this error with a friendly message to help the person executing the script to request an increase in their quota.

Thanks!

**Comment by zerausolrac** [comment]
will be added on next release

**Comment by gleidsonlm** [comment]
On a second review, this seems to happen the script cannot get the authorization token to send requests to Learn. I'm guessing this will happen if:

- The Learn REST API key and secret are not correct;
- The developer has exceed the limit on requests;
- The developer application isn't registered in the Learn site.

I'll keep testing when possible.

Again, thanks! =D

**Comment by zerausolrac** [comment]
It depends on script user on insert the correct credentials, this is not referred to limit of request (10,000 daily). In the case of Learn, users must register API Rest integration on Bb Learn Environment with the  credentials created in developers.blackboad.com
