### ISSUE TITLE
More information on read.me and 

### ISSUE THREAD

**Issue by daveyherrera** [zerausolrac/PyCollab#5]
Hello Carlos,

We need to add a couple of things on the read.me:

First, we need to make sure that our clients understand the following:

In order to get the Learn credentials, they do not to open a case on behind the blackboard nor email developers@blackboard.com.

They need to go to developer.blackboard.com and register from there to grab the Learn credentials for their application, it is also imperative to remind them that they are creating an application based on your code, so they need to register as a developer.

Now, for Collaborate production they CAN and MUST create a ticket on behind the blackboard requesting their credentials.

So, can you please add this in: 

1. Read.me
2. config.py (as comments?)

Appreciate your time and help!

**Comment by zerausolrac** [comment]
the suggested information was added to both files.
