### ISSUE TITLE
Adicionar búsqueda por id de la sesión para los que usan mooodle plugin collaborate

### ISSUE THREAD

**Issue by roxanapmh** [zerausolrac/PyCollab#6]
El código del proyecto PyCollab es muy útil, pero en el caso de nuestra universidad tenemos open LMS con plugin para collaborate ultra no LTI, la búsqueda por nombre de la sesión nos arroja varias grabaciones debido que no se maneja un nombre único de la sesión, nuestros usuarios suelen usar nombres genéricos somo por ejemplo: "Sesión 1".

python CollabMoodle.py -s moodle_plugin_sessions.txt -w 100

![ADJUNTO1](https://user-images.githubusercontent.com/74123378/98574277-b950b100-2285-11eb-9311-f92362d033cc.jpg)

**Comment by zerausolrac** [comment]
Hemos colocado una versión actualizada, Basado en el escenario (Reporte desde Collaborate Manager Institutional – tanto Attendance report  como Recordings report ) se puede utilizar los descrito en el Escenario 3.
